### ISSUE TITLE
To-Do List for Employee Features

### ISSUE THREAD

**Issue by khaCey** [khaCey/project-greensquareadmin#1]
- [ ] Add edit personal details
- [ ] Add edit password
- [ ] Add edit shift times
- [ ] Add force delete for admins, current feature is soft delete.
