### ISSUE TITLE
To-Do-List for Student List

### ISSUE THREAD

**Issue by khaCey** [khaCey/project-greensquareadmin#2]
- [ ] CRUD for Student
- [ ] Server API
- [ ] inquire what features are needed
- [ ] Name
- [ ] Phone
- [ ] Email
- [ ] Paid this month
- [ ] schedule
- [ ] memo
- [ ] student number
